default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: "root"
  password: "password"
  host: "db"
  port: "3306"

development:
  <<: *default
  database: bio_development

production:
  <<: *default
  database: bio_production

test:
  <<: *default
  database: bio_test
